.TH "GIT-USER" "1" "Jul 2016" "git-user v2.0.0" "Git Manual" 
.nh
.ad l
.SH NAME
.PP
git\-user\-rm \- Remove a profile from the current project
.SH SYNOPSIS
.PP
\fBgit\-user rm\fP [OPTIONS]
.SH DESCRIPTION
.PP
Remove a user profile from the default profile for a project.
.SH OPTIONS
.PP
\fB\-G\fP, \fB\-\-global\fP[=false]
    Remove the profile from the global config
.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-c\fP, \fB\-\-config\fP="\~/.git\-profiles"
    config file
.PP
\fB\-g\fP, \fB\-\-git\-path\fP="git"
    The git executable to use
.PP
\fB\-p\fP, \fB\-\-path\fP="."
    The project to get/set the user
.PP
\fB\-V\fP, \fB\-\-version\fP[=false]
    Show the version and exit
.SH SEE ALSO
.PP
\fBgit\-user(1)\fP
