.TH "GIT-USER" "1" "Jun 2017" "git-user v2.0.5" "Git Manual" 
.nh
.ad l
.SH NAME
.PP
git\-user\-list \- List all saved profiles
.SH SYNOPSIS
.PP
\fBgit\-user list [flags]\fP
.SH DESCRIPTION
.PP
List all of the saved user profiles found in your config.
.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for list
.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-c\fP, \fB\-\-config\fP="\~/.git\-profiles"
    config file
.PP
\fB\-g\fP, \fB\-\-git\-path\fP="git"
    The git executable to use
.PP
\fB\-p\fP, \fB\-\-path\fP="."
    The project to get/set the user
.PP
\fB\-V\fP, \fB\-\-version\fP[=false]
    Show the version and exit
.SH SEE ALSO
.PP
\fBgit\-user(1)\fP
