.TH "GIT-USER" "1" "Jun 2017" "git-user v2.0.5" "Git Manual" 
.nh
.ad l
.SH NAME
.PP
git\-user \- Allows you to save multiple user profiles and set them as git project defaults
.SH SYNOPSIS
.PP
\fBgit\-user [flags]\fP
.SH DESCRIPTION
.PP
git\-user lets you quickly switch between multiple git user profiles
.SH OPTIONS
.PP
\fB\-c\fP, \fB\-\-config\fP="\~/.git\-profiles"
    config file
.PP
\fB\-g\fP, \fB\-\-git\-path\fP="git"
    The git executable to use
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for git\-user
.PP
\fB\-p\fP, \fB\-\-path\fP="."
    The project to get/set the user
.PP
\fB\-V\fP, \fB\-\-version\fP[=false]
    Show the version and exit
.SH SEE ALSO
.PP
\fBgit\-user\-add(1)\fP, \fBgit\-user\-del(1)\fP, \fBgit\-user\-edit(1)\fP, \fBgit\-user\-list(1)\fP, \fBgit\-user\-rm(1)\fP, \fBgit\-user\-set(1)\fP
