.TH "GIT-USER" "1" "Jul 2016" "git-user v2.0.0" "Git Manual" 
.nh
.ad l
.SH NAME
.PP
git\-user\-del \- Delete a profile
.SH SYNOPSIS
.PP
\fBgit\-user del\fP [OPTIONS]
.SH DESCRIPTION
.PP
Delete a user profile from your config.
.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-c\fP, \fB\-\-config\fP="\~/.git\-profiles"
    config file
.PP
\fB\-g\fP, \fB\-\-git\-path\fP="git"
    The git executable to use
.PP
\fB\-p\fP, \fB\-\-path\fP="."
    The project to get/set the user
.PP
\fB\-V\fP, \fB\-\-version\fP[=false]
    Show the version and exit
.SH SEE ALSO
.PP
\fBgit\-user(1)\fP
