# Golang CircleCi config v1.18.1
version: 2
jobs:
  build-deps:
    docker:
      - image: gesquive/go-builder:latest
    steps:
      - run: cci-clone
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: make deps
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "{{ .Environment.GOPATH }}/vendor/go/pkg/mod"

  test-app:
    docker:
      - image: gesquive/go-builder:latest
    steps:
      - run: cci-clone
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: make
      - run: make test

  coverage:
    docker:
      - image: gesquive/go-builder:latest
    steps:
      - run: cci-clone
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: make coverage-report
      - store_artifacts:
          path: coverage
      - run: codecov-bash -f coverage/coverage.dat
    
  release-app-snapshot:
    docker:
      - image: gesquive/go-builder:latest
    steps:
      - run: cci-clone
      - run: make release-snapshot
      - save_cache:
          key: go-snap-v1-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  release-app-build:
    docker:
      - image: gesquive/go-builder:latest
    steps:
      - run: cci-clone
      - run: make release
      - save_cache:
          key: go-dist-v1-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  release-docker-snapshot:
    docker:
      - image: gesquive/docker-builder:latest
    steps:
      - run: cci-clone
      - restore_cache:
          keys:
            - go-snap-v1-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker:
          version: 19.03.13
      - run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN $DOCKER_REGISTRY
      - run: docker info
      - run: docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: make release-docker-snapshot

  release-docker-build:
    docker:
      - image: gesquive/docker-builder:latest
    steps:
      - run: cci-clone
      - restore_cache:
          keys:
            - go-dist-v1-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker:
          version: 19.03.13
      - run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN $DOCKER_REGISTRY
      - run: docker info
      - run: docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: make release-docker
    

workflows:
  version: 2
  go-build:
    jobs:
      - build-deps:
          filters:
            tags:
              only: /.*/
      - test-app:
          requires:
            - build-deps
      - coverage:
          requires:
            - build-deps
      - release-app-snapshot:
          requires:
            - build-deps
          filters:
            tags:
              ignore: /^v.*/
      - release-app-build:
          context: github-deploy
          requires:
            - build-deps
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
              ignore: /.*/
      - release-docker-snapshot:
          context: docker-deploy
          requires:
            - release-app-snapshot
          filters:
            tags:
              ignore: /^v.*/
      - release-docker-build:
          context: docker-deploy
          requires:
            - release-app-build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
              ignore: /.*/
